apiVersion: v2
appVersion: 1.26.7
description: A Helm chart to run NodeLocal DNSCache in Kubernetes clusters
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
home: https://github.com/giantswarm/k8s-dns-node-cache-app
name: k8s-dns-node-cache-app
version: 2.9.1
annotations:
  io.giantswarm.application.team: cabbage
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
  gpuInstances: false
