apiVersion: v2
appVersion: 1.26.7
description: A Helm chart to run NodeLocal DNSCache in Kubernetes clusters
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
home: https://github.com/giantswarm/k8s-dns-node-cache-app
name: k8s-dns-node-cache-app
version: 2.9.2
annotations:
  io.giantswarm.application.team: cabbage
  io.giantswarm.application.audience: "all"
  io.giantswarm.application.managed: "false"
  io.giantswarm.application.restrictions.cluster-singleton: "true"
  io.giantswarm.application.restrictions.fixed-namespace: kube-system
  io.giantswarm.application.restrictions.gpu-instances: "false"
